### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by DeividAndreola** [wurlyfox/crashutils#1]
Textures exported becomes blue. 
![1 copy](https://cloud.githubusercontent.com/assets/11369917/10156576/1844cbb8-6659-11e5-8214-bfbf9115ba1e.png)

**Comment by warenhuis** [comment]
If you export to TGA files you must flip the RGB colorvalues in reverse (so BGR). That's why all the colors are ' blue-ish'. Should be a minor adjustment to the source code.

**Comment by ManDude** [comment]
I'm pretty sure every image-editing program has some sort of RGB remap function that you can use to swap blue with red to get accurate colors.
